server:
  port:
    4002

spring:
  application:
    name: music-streaming

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      spring.json.add.type.headers: false

  elasticsearch:
    uris: http://localhost:9200

  servlet:
    multipart:
      enabled: true



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6700/eureka

